apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: securechain
  labels:
    app: backend
    environment: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        environment: production
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: backend
          image: ghcr.io/ebak555/securechain-backend:sha-6ce17ced033da8b90c86cdc0f7af9fb262200fda
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
