apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "87.2.1"
    helm:
      releaseName: monitoring
      valueFiles: []
      values: |
        alertmanager:
          enabled: false
        grafana:
          enabled: true
          replicas: 1
          service:
            type: LoadBalancer
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 256Mi
          adminPassword: "securechain-grafana"
        prometheus:
          prometheusSpec:
            replicas: 1
            retention: 7d
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 1Gi
            additionalScrapeConfigs:
              - job_name: falcosidekick
                static_configs:
                  - targets: ["falco-falcosidekick.falco.svc.cluster.local:2802"]
              - job_name: kyverno
                static_configs:
                  - targets: ["kyverno-admission-controller.kyverno.svc.cluster.local:8000"]
        kube-state-metrics:
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
        prometheus-node-exporter:
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
